<?php
return [
    'EXTENSIONS' => [
        'backend' => [
            'backendFavicon' => '',
            'backendLogo' => '',
            'loginBackgroundImage' => '',
            'loginFootnote' => '',
            'loginHighlightColor' => '',
            'loginLogo' => '',
            'loginLogoAlt' => '',
        ],
        'extensionmanager' => [
            'automaticInstallation' => '1',
            'offlineMode' => '0',
        ],
        'news' => [
            'advancedMediaPreview' => '1',
            'archiveDate' => 'date',
            'categoryBeGroupTceFormsRestriction' => '0',
            'categoryRestriction' => '',
            'contentElementRelation' => '1',
            'dateTimeNotRequired' => '0',
            'hidePageTreeForAdministrationModule' => '0',
            'manualSorting' => '0',
            'pageTreePluginPreview' => '1',
            'prependAtCopy' => '1',
            'resourceFolderImporter' => '/news_import',
            'rteForTeaser' => '0',
            'showAdministrationModule' => '1',
            'slugBehaviour' => 'unique',
            'storageUidImporter' => '1',
            'tagPid' => '1',
        ],
        'ns_t3ai' => [
            'apiKey' => '',
            'model' => 'gpt-3.5-turbo',
            'openAiPromptPrefixPageTitle' => 'Act as an SEO expert and write five an optimized title tag for a web page about [Content]',
        ],
        'redirects' => [
            'showCheckIntegrityInfoInReports' => '1',
            'showCheckIntegrityInfoInReportsSeconds' => '86400',
        ],
        'scheduler' => [
            'maxLifetime' => '1440',
        ],
        'xima_typo3_content_planner' => [
            'autoAssignment' => '1',
            'clearCommentsOnStatusReset' => '1',
            'commentTodos' => '1',
            'currentAssigneeHighlight' => '1',
            'enableContentElementSupport' => '1',
            'enableFilelistSupport' => '1',
            'recordEditHeaderInfo' => '1',
            'recordListStatusInfo' => '1',
            'resetContentElementStatusOnPageReset' => '0',
            'treeStatusInformation' => 'comments',
            'webListHeaderInfo' => '1',
        ],
        'xima_typo3_frontend_edit' => [
            'enableSaveAndCloseButton' => '1',
            'forceReturnUrlGeneration' => '0',
            'frontendDebugMode' => '0',
            'linkTargetBlank' => '0',
            'useRedirect' => '0',
        ],
    ],
];
